version: "1.0"
info:
  model: int-scaffold
packages:
- name: RAHS_ERT_UpgradeProject
  gitServerName: RAHS with Space
  gitUrl: https://github.com/rahuldemocenter/RAHS_ERT_UpgradeProject
  gitUsername: rahuldemocenter
  gitBranch: main
- name: TestWIE1344
  gitServerName: RAHS_Not_SAG
  gitUrl: https://github.com/rahuldemocenter
  gitUsername: rahuldemocenter
  gitBranch: main
services:
- serviceName: project.rahs_ert_upgrade.integrations:EFS_Debug
  packages:
  - name: RAHS_ERT_UpgradeProject
    version: "1.0"
  - name: TestWIE1344
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.rahs_ert_upgrade.integrations:EFS_PackageService
  packages:
  - name: RAHS_ERT_UpgradeProject
    version: "1.0"
  - name: TestWIE1344
    version: "1.0"
- serviceName: TestWIE1344.services:addInt
  packages:
  - name: TestWIE1344
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
configurationVariables:
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  jdbc.jdbcTestPool.expireTime: "60000"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  jdbc.jdbcTestPool.spyenabled: "false"
  jdbc.jdbcTestPool.snoopenabled: "false"
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  jdbc.jdbcTestPool.useSSL: "false"
